version: '3.4'

services:
  db:
    container_name: justasecond.db
    #image: beercan1989/arm-mysql:latest
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: justasecond
      MYSQL_USER: justasecondadmin
      MYSQL_PASSWORD: 7uJ0dlVTjeYW
      MYSQL_ROOT_PASSWORD: doku3heNQB3t
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3306'
    expose:
      - '3306'

  justasecond.web:
    image: ${DOCKER_REGISTRY-}justasecondweb
    build:
      context: .
      dockerfile: JustASecond.Web/Dockerfile